### ISSUE TITLE
timeout expired waiting for volumes to attach/mount for pod

### ISSUE THREAD

**Issue by scottrobertson** [StackPointCloud/digitalocean-flex-volume#9]
```
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: doclaim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: digitalocean

---

apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - image: nginx
    name: nginx-demo
    ports:
      - name: web
        containerPort: 80
        protocol: TCP
    volumeMounts:
      - name: html
        mountPath: "/usr/share/nginx/html"
  volumes:
  - name: html
    persistentVolumeClaim:
      claimName: doclaim
```

Getting the error:

```
  Warning  FailedMount            30s   kubelet, spck5hh55n-worker-1  Unable to mount volumes for pod "test_default(28f0ce36-4746-11e8-86dd-bea08d3d0487)": timeout expired waiting for volumes to attach/mount for pod "default"/"test". list of unattached/unmounted volumes=[html]
```
